services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend_questions
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - .:/var/www

  db:
    image: postgres:15.3-alpine
    container_name: database_questions
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend


networks:
  backend:

volumes:
  postgres_data: